// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKaM77Rn0sJ4MstOLhnppO6-lwHs0Q8Ao',
    appId: '1:270809684516:web:de37833740328c6f48d6b1',
    messagingSenderId: '270809684516',
    projectId: 'todo-ee57b',
    authDomain: 'todo-ee57b.firebaseapp.com',
    storageBucket: 'todo-ee57b.appspot.com',
    measurementId: 'G-0MLW4E7DVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG7gROdzi-tArUSaMBJ6EZzg3gnf9LJ7Y',
    appId: '1:270809684516:android:cdd37a82f190858648d6b1',
    messagingSenderId: '270809684516',
    projectId: 'todo-ee57b',
    storageBucket: 'todo-ee57b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoNd5tcC2Nsi08e6qSAbq0nyTXGd5CG9Q',
    appId: '1:270809684516:ios:92b1c36ac50995f648d6b1',
    messagingSenderId: '270809684516',
    projectId: 'todo-ee57b',
    storageBucket: 'todo-ee57b.appspot.com',
    iosClientId: '270809684516-f738781p9u6se923g3huc8ogd1r850bc.apps.googleusercontent.com',
    iosBundleId: 'ditto.todo.flutterTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoNd5tcC2Nsi08e6qSAbq0nyTXGd5CG9Q',
    appId: '1:270809684516:ios:92b1c36ac50995f648d6b1',
    messagingSenderId: '270809684516',
    projectId: 'todo-ee57b',
    storageBucket: 'todo-ee57b.appspot.com',
    iosClientId: '270809684516-f738781p9u6se923g3huc8ogd1r850bc.apps.googleusercontent.com',
    iosBundleId: 'ditto.todo.flutterTodo',
  );
}
